lottery:
    debug_mode: true
    ticket_price: 10
    pot: 0
    time: 16
    max_tickets: 50
    channel_name: global
        
#  Possible permission nodes
#
#    lottery.general - provides access to all basic commands (help, buy, winners)
#    lottery.admin - provides access to all admin commands (config, addtopot, removefrompot, draw)
#