lottery:
    using_iconomy: true
    using_permissions: true
    debug_mode: true
    ticket_price: 10
    pot: 0
    time: 16
    max_tickets: 50
    
mysql:
    server:
        address: localhost
        port: 8889
        username: root
        password: root
    database:
        name: kingdoms
        table_prefix: lottery_
        
#  Possible permission nodes
#
#    lottery.general - provides access to all basic commands (help, buy, winners)
#    lottery.admin - provides access to all admin commands (config, addtopot, removefrompot, draw)
#